name: lor_deck_codes_dart
description: Dart library for decoding and encoding decks in Legend of Runeterra.
version: 1.0.2
homepage: https://github.com/edenizk/lor_deck_codes_dart

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  fixnum: ^0.10.11


dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
